name = "meowtrail"
compatibility_date = "2026-06-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "meowtrail_users"
database_name = "meowtrail-users"
database_id = "80cc8484-7f17-43a0-96aa-14809d953c26"
